fix(wl_data_device): drop and leave event handling
Smithay/client-toolkit pull request #409
Opened 2023-09-22 05:14 UTC by wash2

While the spec says to destroy the wl_data_offer after wl_data_device::leave, I think compositors often send the leave event right away after a drop. This is a bit problematic if an application hasn't finished receiving the data and then the data offer is destroyed before it can make the finish request. I believe this can currently be recreated in the data_device example. The source never receives a finish event because the offer was destroyed and isn't alive by the time we make the request.

This PR tries to avoid destroying an offer after the leave event if a drop event already occurred. It also tries to avoid making request besides finish or destroy.

2023-09-22 19:22 UTC, kchibisov requested changes
We should probably document that the users should destroy the offer? It would also be nice to get which compositors do what you say in particular, but just for the reference.

2023-09-22 19:24 UTC, wash2 commented on examples/data_device.rs
> +        println!("FINISHED");
O just copied the message above it, but I can change how both messages are written.

2023-09-22 19:28 UTC, wash2 commented
> It would also be nice to get which compositors do what you say in particular, but just for the reference.

So far I was able to recreate the issue in Cosmic, sway, and Pop on wayland (Gnome), but I can double check vanilla Gnome too

2023-09-22 19:34 UTC, kchibisov commented
>So far I was able to recreate the issue in Cosmic, sway, and Pop on wayland (Gnome), but I can double check vanilla Gnome too

That's more than enough I guess, just mention that in the commit. We could probably use some RAII so users won't worry about that, but I'm not familiar with dnd myself much and can just look into the code.

2023-09-22 19:41 UTC, kchibisov commented on src/data_device_manager/data_offer.rs
> +    }
Do we really need this as a separate function if it's used only once in `Drop` handler?

2023-09-22 19:41 UTC, kchibisov commented on src/data_device_manager/data_offer.rs
> +            receive(&self.data_offer, mime_type)
Could you document why it's like that?

2023-09-22 20:08 UTC, wash2 commented on src/data_device_manager/data_offer.rs
> +            receive(&self.data_offer, mime_type)
I've added a comment that explains why

2023-09-22 20:10 UTC, kchibisov approved these changes

2023-09-23 19:33 UTC, elinorbgr approved these changes

2023-09-23 19:34 UTC, merged